// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStarted: [
    { type: 'autogenerated', dirName:'getting-started' },
  ],
  userGuide: [
    { type: 'autogenerated', dirName:'user-guide' },
  ],
  policies: [
    { type: 'autogenerated', dirName:'policies' },
  ],
  api: [
    { type: 'autogenerated', dirName:'api' },
  ],
  examples: [
    { type: 'autogenerated', dirName:'examples' },
  ],
};

export default sidebars;
